### ISSUE TITLE
bug em palavras reservadas e identificadores

### ISSUE THREAD

**Issue by moabson** [moabson/JCAM#1]
Problema aparece quando um carácter não esperado aparece em palavras reservadas e identificadores (pelo menos os dois q testei).

Exemplo (loop infinito):
**var** myVari@vel : **inteiro**;

No caso do _underscore_ só da problema (loop infinito) quando ele aparece no inicio da palavra.

**var** _teste : **texto** = "André";
_**escreva** ("Olá");

**Comment by jcarlosadm** [comment]
Quando o underscore (ou outro caractere inválido) aparece no início de um token, ele não entra no while principal do método `nextToken` ( `while (this.isValidToken(charValue) || this.canGrown(charValue))`), pois não é caractere válido nem pode aumentar (não é parte de um caractere válido). Assim, a variável `currentColumnNumber` não é incrementada, e o mesmo caractere é analisado novamente na próxima chamada do `nextToken`, e de novo, e de novo....

antes do `while`, um `if` resolve.

**Comment by jcarlosadm** [comment]
if (!this.isValidToken(charValue) && !this.canGrown(charValue))
			++this.currentColumnNumber;

**Comment by jcarlosadm** [comment]
if (!this.isValidToken(charValue) && !this.canGrown(charValue))
			++this.currentColumnNumber;

**Comment by jcarlosadm** [comment]
```
if (!this.isValidToken(charValue) && !this.canGrown(charValue))
    ++this.currentColumnNumber;
```

**Comment by jcarlosadm** [comment]
realizado commit com solução
